version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  notification-service:
    build:
      context: .
    container_name: notification-service
    ports:
      - "8080:8080" # Expose the notification service on port 8080
    depends_on:
      - rabbitmq # Ensure RabbitMQ starts before the notification service
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672